### ISSUE TITLE
Implement a flip card button. 150 pts

### ISSUE THREAD

**Issue by kevinwalau** [ucsb-cs56-projects/cs56-games-name-memorization#17]
Create a flip button that would flip the card when pressed as opposed to the current method of clicking on two separate buttons to view each side. Should also add a flipping animation to enhance game play.

**Comment by jrcryan** [comment]
approved
~200 points

**Comment by Tektonbuilds** [comment]
This is not a super hard animation but, redoing the GUI might take a while.

Estimated: 150 points

**Comment by Tektonbuilds** [comment]
F16 READY!

**Comment by aryamandas** [comment]
F17 OK (150 points)

**Comment by aryamandas** [comment]
W18 OK (150 points)

**Comment by MatthewPontarolo** [comment]
Flip button has functionality, but no animation.

Issue should be changed to "Create animation with flip", estimated at 100 points.

**Comment by aryamandas** [comment]
W18 OK (50 points)
- points awarded for implementation of flip button and functionality - animation should still be attempted in another issue
