### ISSUE TITLE
Switching between different menu options

### ISSUE THREAD

**Issue by tkyngo** [UCSB-CS56-Projects/cs56-games-name-memorization#18]
Make it so that with each menu option it DOES NOT open a new window but just clears all the components of the existing state and adds all components for the new state. (i.e. when player chooses "Play" it clears all main menu components and switches to the play mode with all of "Play's" components in the same window).

**Comment by jrcryan** [comment]
approved
~100 points

**Comment by EasterAndJay** [comment]
Closed
