### ISSUE TITLE
Add jUnit tests for existing code. 100 pts

### ISSUE THREAD

**Issue by andrewberls** [UCSB-CS56-Projects/cs56-games-name-memorization#2]
The code already in place has no accompanying unit tests. A minimal set of jUnit tests should be added for each class.

~estimated 150

**Comment by Tektonbuilds** [comment]
I am not sure how you would do a JUnit test but if it can be done, sure.

Estimated: 100 points

**Comment by Tektonbuilds** [comment]
F16 READY!
