### ISSUE TITLE
Add a Quiz Mode. 200 pts

### ISSUE THREAD

**Issue by jimmylle** [UCSB-CS56-Projects/cs56-games-name-memorization#22]
Make it so that the user can enter a quiz mode and have quizzes for specific decks. This quiz would be interactive because it would show you the definition of a term/card and then the user would have to type in the word/term belonging to that definition instead of just using the program to look at the term and definition. The user would probably have to enter the exact word or the developer can make it more flexible in what the correct answer is. It's also possible to add an override button so that if the user actually typed in the right word but just had a typo it would still count.

~225 points

**Comment by Tektonbuilds** [comment]
Making a quiz mode shouldn't take too long unless the GUI is extensively redone. You can follow the quizlet example of how they quiz people.

Estimated: 200 points

**Comment by Tektonbuilds** [comment]
F16 READY!
