### ISSUE TITLE
Visually improve the GUI. 200 pts

### ISSUE THREAD

**Issue by KevinLee00** [UCSB-CS56-Projects/cs56-games-name-memorization#23]
Right now, the program visually looks very unappealing. 
Possible GUI Improvements/Suggestions
1. We should use less contrasting colors more subtle colors compliments. (ie. Instead of blue, orange, and bright green, we use different blues and white). 
2. The text boxes should be more obvious. At the moment, they're just white boxes. Perhaps deboss the text boxes to make it more obvious that it's a text box element on screen. 
3. The two columns on each side are not the same size making the program look asymmetrical and plain ugly. 
4. Button placement could also be more spaced out instead of sticking them directly next to each other.
5. (OPTIONAL) Instead of using basic Swing components (which are pretty ugly to be honest), you could use more sophisticated GUI packages such as JavaFX. 

~250 Points

**Comment by EasterAndJay** [comment]
W16 approved tentatively

**Comment by Tektonbuilds** [comment]
Don't spend too long on improving the GUI. This should be a second priority but it would be nice to make it more aesthetically appealing. 

Estimated: 200 points

**Comment by Tektonbuilds** [comment]
F16 READY!
