### ISSUE TITLE
Fix bugs

### ISSUE THREAD

**Issue by drdipepperjr** [UCSB-CS56-Projects/cs56-games-name-memorization#28]
There are some bugs in the code right now

- Using the "Edit" feature, it replaces all of the current card's text with "Enter Text". It should read in the current text so the user can remember what they wrote in.
- There is currently no way to exit the "add" menu unless you add a card. You should be able to leave the screen if you don't want to add a card (same with edit; you have to edit the card to leave).
-  The GUI doesn't update when changing between decks (it does update the card viewer though). Should output the current deck's name, number of cards, and current card number. 
- You can add a deck that has the same name as another deck. You can also add a deck that has no name. This should not happen. 
- If the first deck in the deckList is empty, the GUI will not read "Deck is currently empty", it will display a blank card.

**Comment by EasterAndJay** [comment]
Approved 200 points

**Comment by drdipepperjr** [comment]
Done! All bugs above are fixed. You can also exit the "Select" menu as well.

**Comment by EasterAndJay** [comment]
Closed
