### ISSUE TITLE
Implement Multiple Decks

### ISSUE THREAD

**Issue by cbia4** [UCSB-CS56-Projects/cs56-games-name-memorization#5]
Implement a user interface that lets the user create a new deck, view decks already created, load and save the current deck, and delete a deck.

**Comment by tkyngo** [comment]
Started on multiple decks, but hasn't been implemented completely. Rest can be assigned to the next class.

**Comment by drdipepperjr** [comment]
Done! You can now have multiple decks, name them, edit them, select the current working deck, remove them, and save/load them. GUI does not reflect the name of the current deck, however.

**Comment by EasterAndJay** [comment]
Approved for 400 points

**Comment by EasterAndJay** [comment]
Closed
