### ISSUE TITLE
Create menu. 100 pts

### ISSUE THREAD

**Issue by jennacryan** [UCSB-CS56-Projects/cs56-games-name-memorization#8]
Create a menu with options and an instructions page rather than launching right into the game screen

~200 points

**Comment by kevinwalau** [comment]
We created a function menu page with instructions that also appear on screen when prompted. We also added other features such as a practice mode where you can play the game without keeping track of score (how many points would this be?). There's also an addition of a cancel button when adding/editing cards (how many points would this be?).

**Comment by jrcryan** [comment]
-menu page looks good
-practice mode does not work and the button to return to the main menu does not work
-nowhere to go from add/edit screen, add functionality and return to main menu/exit options

**Comment by EasterAndJay** [comment]
W16 ok tentative

**Comment by Tektonbuilds** [comment]
I don't see a menu so that may still need to be worked on. This should take at most 4 hours.

Estimated: 100 points.

**Comment by Tektonbuilds** [comment]
F16 READY!

**Comment by aryamandas** [comment]
F17 OK (150 pts)
