### ISSUE TITLE
Document code

### ISSUE THREAD

**Issue by jrcryan** [UCSB-CS56-Projects/cs56-games-name-memorization#9]
Current code is very sparse on comments. Provide good documentation about functionality of current code (and any code you add)

~100 points

**Comment by kevinwalau** [comment]
Added comments to the class files on each method, and also created a documentation text file that gives a general summary of each file.

**Comment by jrcryan** [comment]
documentation should be with the code, and it is still very sparse 
info on proper javadoc documentation: http://www.tutorialspoint.com/java/java_documentation.htm

**Comment by drdipepperjr** [comment]
Code was documented by me a few days ago. All the new code the I added has also been documented.

**Comment by EasterAndJay** [comment]
Closed
